# Copyright 2025 Pasteur Labs. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

# Tesseract API module for PIC-ROM optimization
# Generated by tesseract 1.1.1 on 2026-01-03T23:54:02.020022

import sys
import os
import uuid
import glob

# Add module directory to Python path to find local modules
# Works both in Docker (/tesseract) and locally (directory containing this file)
if os.path.exists('/tesseract'):
    # Docker environment
    if '/tesseract' not in sys.path:
        sys.path.insert(0, '/tesseract')
else:
    # Local environment - add directory containing this file
    current_dir = os.path.dirname(os.path.abspath(__file__))
    if current_dir not in sys.path:
        sys.path.insert(0, current_dir)

import jax
import jax.numpy as jnp
import numpy as np
from pydantic import BaseModel, Field
from tesseract_core.runtime import Array, Float32, Float64
from tesseract_core.runtime.experimental import log_artifact, log_metric, log_parameter

from pic_simulation import PICSimulation
from control import FourierActuator, build_rfftn_modes_single
from optimize import Optimizer
from plotting import scatter_animation, plot_pde_solution, plot_modes

#
# Schemas
#


class InputSchema(BaseModel):
    """Input schema for PIC-ROM optimization."""
    # Simulation parameters
    N_particles: int = Field(default=40000, description="Number of particles")
    N_mesh: int = Field(default=400, description="Number of mesh cells")
    t1: float = Field(default=20.0, description="Time at which simulation ends")
    dt: float = Field(default=0.1, description="Timestep")
    boxsize: float = Field(default=50.0, description="Periodic domain [0,boxsize]")
    n0: float = Field(default=1.0, description="Electron number density")
    vb: float = Field(default=3.0, description="Beam velocity")
    vth: float = Field(default=1.0, description="Beam width")
    pos_sample: bool = Field(default=False, description="Whether to sample positions randomly")
    
    # Optimization parameters
    n_steps: int = Field(default=10, description="Number of optimization steps")
    lr: float = Field(default=1e-1, description="Learning rate")
    seed: int = Field(default=0, description="Random seed")
    
    # Initial modes parameters (for FourierActuator initialization)
    mode_n: int = Field(default=1, description="Time mode index")
    mode_m: int = Field(default=1, description="Space mode index")
    mode_A: float = Field(default=1e5, description="Mode amplitude")
    mode_phi_t: float = Field(default=0.0, description="Time phase")
    mode_phi_x: float = Field(default=0.0, description="Space phase")


class OutputSchema(BaseModel):
    """Output schema for PIC-ROM optimization."""
    train_losses: Array[(None,), Float64] = Field(description="Training losses at each optimization step")
    final_loss: float = Field(description="Final training loss")
    
    # Simulation results after optimization
    positions: Array[(None, None), Float32] = Field(description="Particle positions over time (Nt, Np)")
    velocities: Array[(None, None), Float32] = Field(description="Particle velocities over time (Nt, Np)")
    E_field: Array[(None, None), Float32] = Field(description="Electric field over time (Nt, N_mesh)")
    E_ext: Array[(None, None), Float32] = Field(description="External electric field over time (Nt, N_mesh)")
    rho: Array[(None, None), Float32] = Field(description="Density over time (Nt, N_mesh)")
    momentum: Array[(None, None), Float32] = Field(description="Momentum over time (Nt, N_mesh)")
    energy: Array[(None, None), Float32] = Field(description="Energy over time (Nt, N_mesh)")
    ts: Array[(None,), Float32] = Field(description="Time array")


#
# Required endpoints
#


def apply(inputs: InputSchema) -> OutputSchema:
    """Run PIC simulation optimization with Fourier actuator control."""
    # Set up random key
    key = jax.random.key(inputs.seed)
    key1, key2, key3 = jax.random.split(key, num=3)
    
    # Initialize particle positions
    if inputs.pos_sample:
        pos = jax.random.uniform(key1, (inputs.N_particles, 1)) * inputs.boxsize
    else:
        pos = jnp.zeros(inputs.N_particles)
        for i in range(inputs.N_particles):
            pos = pos.at[i].set(i * inputs.boxsize / inputs.N_particles)
        pos = jax.random.choice(key1, pos, shape=pos.shape, replace=False)
        pos = pos[:, None]
    
    # Initialize particle velocities
    vel = inputs.vth * jax.random.normal(key2, (inputs.N_particles, 1)) + inputs.vb
    Nh = int(inputs.N_particles / 2)
    vel = vel.at[Nh:].set(-1 * vel[Nh:])
    
    y0 = (pos, vel)
    
    # Initialize PIC simulation
    pic = PICSimulation(
        inputs.boxsize, inputs.N_particles, inputs.N_mesh, 
        inputs.n0, inputs.dt, inputs.t1, t0=0, higher_moments=True
    )
    
    # Initialize Fourier actuator modes
    modes = build_rfftn_modes_single(
        pic.n_steps, pic.N_mesh, 
        n=inputs.mode_n, m=inputs.mode_m, 
        A=inputs.mode_A, phi_t=inputs.mode_phi_t, phi_x=inputs.mode_phi_x
    )
    modes = jnp.zeros_like(modes[:11, :11])
    
    E_control = FourierActuator(pic.n_steps, pic.N_mesh, modes=modes)
    
    # Determine run directory before optimization (so checkpoints can be saved there)
    base_dir = os.path.dirname(os.path.abspath(__file__))
    cwd = os.getcwd()
    
    # Check if current working directory is a run directory
    if os.path.basename(cwd).startswith('run_') and os.path.isdir(cwd):
        run_dir = cwd
    else:
        # Check for Tesseract environment variable
        run_id = os.environ.get('TESSERACT_RUN_ID')
        if run_id:
            run_dir = os.path.join(base_dir, f"run_{run_id}")
        else:
            # Find run directories with logs and pick the one with most recently modified log file
            run_dirs = glob.glob(os.path.join(base_dir, "run_*"))
            if run_dirs:
                # Find run directories with logs and get their most recent log file modification time
                run_dir_candidates = []
                for rd in run_dirs:
                    logs_dir = os.path.join(rd, "logs")
                    if os.path.isdir(logs_dir):
                        log_files = glob.glob(os.path.join(logs_dir, "*.log")) + \
                                   glob.glob(os.path.join(logs_dir, "*.csv"))
                        if log_files:
                            # Get the most recent modification time of log files in this run directory
                            max_mtime = max(os.path.getmtime(f) for f in log_files)
                            run_dir_candidates.append((max_mtime, rd))
                
                if run_dir_candidates:
                    # Sort by most recent log file modification time
                    run_dir_candidates.sort(key=lambda x: x[0], reverse=True)
                    run_dir = run_dir_candidates[0][1]
                else:
                    # No run directories with logs, use the most recently created run directory
                    run_dirs.sort(key=os.path.getmtime, reverse=True)
                    run_dir = run_dirs[0]
            else:
                # No run directories exist, create a new one
                run_id = str(uuid.uuid4())
                run_dir = os.path.join(base_dir, f"run_{run_id}")
    
    # Set up model checkpoint directory in run directory
    model_dir = os.path.join(run_dir, "model")
    os.makedirs(model_dir, exist_ok=True)
    # Ensure trailing separator for path concatenation in optimize.py
    # (optimize.py uses string concatenation: save_dir + save_name)
    if not model_dir.endswith("/"):
        model_dir = model_dir + "/"
    
    # Log optimization parameters
    log_parameter("n_steps", inputs.n_steps)
    log_parameter("lr", inputs.lr)
    log_parameter("seed", inputs.seed)
    log_parameter("N_particles", inputs.N_particles)
    log_parameter("N_mesh", inputs.N_mesh)
    log_parameter("t1", inputs.t1)
    log_parameter("dt", inputs.dt)
    log_parameter("boxsize", inputs.boxsize)
    
    # Define loss metric
    def loss_metric(pic):
        energy = jnp.mean((pic.E_field + pic.E_ext) ** 2)
        return energy
    
    # Define logging callback for optimizer
    def log_callback(log_type, **kwargs):
        if log_type == "loss":
            log_metric("train_loss", kwargs["loss"], step=kwargs["step"])
            log_metric("step_time", kwargs["step_time"], step=kwargs["step"])
        elif log_type == "checkpoint":
            # Log checkpoint as artifact
            checkpoint_path = kwargs["checkpoint_path"]
            if os.path.exists(checkpoint_path):
                log_artifact(checkpoint_path)
        elif log_type == "training_complete":
            pass  # Can add completion logging if needed
    
    # Run optimization with checkpoints saved in run directory
    optimizer = Optimizer(
        pic=pic, y0=y0, model=E_control, 
        loss_metric=loss_metric, lr=inputs.lr,
        save_dir=model_dir
    )
    
    E_control, train_losses, _ = optimizer.train(
        n_steps=inputs.n_steps,
        save_every=100,
        seed=inputs.seed,
        print_status=True,
        log_callback=log_callback
    )
    
    # Run final simulation with optimized control
    pic = PICSimulation(
        inputs.boxsize, inputs.N_particles, inputs.N_mesh,
        inputs.n0, inputs.dt, inputs.t1, t0=0, higher_moments=True
    )
    
    pic = pic.run_simulation(y0, E_control=E_control)
    
    # Log final training loss
    if len(train_losses) > 0:
        log_metric("final_loss", float(train_losses[-1]))
    
    # Use the same run_dir that was determined before optimization
    # (run_dir is already set from the optimization section above)
    plots_dir = os.path.join(run_dir, "plots")
    os.makedirs(plots_dir, exist_ok=True)
    
    # Plot external field
    u = jax.vmap(E_control)(pic.ts)
    external_field_path = os.path.join(plots_dir, "external_field.png")
    plot_pde_solution(pic.ts, u, inputs.boxsize, name=r"External field", label=r"$E_{ext}$", save_path=external_field_path)
    if os.path.exists(external_field_path):
        log_artifact(external_field_path)
    
    # Scatter animation
    scatter_path = os.path.join(plots_dir, "scatter.mp4")
    scatter_animation(pic.ts, pic.positions, pic.velocities, Nh, boxsize=inputs.boxsize, k=1, fps=10, save_path=scatter_path)
    if os.path.exists(scatter_path):
        log_artifact(scatter_path)
    
    # Plot density, momentum, energy
    density_path = os.path.join(plots_dir, "density.png")
    plot_pde_solution(pic.ts, pic.rho, inputs.boxsize, name=r"Density", label=r"$\rho$", save_path=density_path)
    if os.path.exists(density_path):
        log_artifact(density_path)
    
    momentum_path = os.path.join(plots_dir, "momentum.png")
    plot_pde_solution(pic.ts, pic.momentum, inputs.boxsize, name=r"Momentum", label=r"$P$", save_path=momentum_path)
    if os.path.exists(momentum_path):
        log_artifact(momentum_path)
    
    energy_path = os.path.join(plots_dir, "energy.png")
    plot_pde_solution(pic.ts, pic.energy, inputs.boxsize, name=r"Energy", label=r"$E$", save_path=energy_path)
    if os.path.exists(energy_path):
        log_artifact(energy_path)
    
    # Plot modes (these create multiple files, so we log all of them)
    density_modes_base = os.path.join(plots_dir, "density_modes")
    plot_modes(pic.ts, pic.rho, max_mode_spect=10, max_mode_time=5, boxsize=inputs.boxsize, num=4, zero_mean=True, save_path=density_modes_base)
    for suffix in ["_spectrum.png", "_evolution.png"]:
        mode_path = density_modes_base + suffix
        if os.path.exists(mode_path):
            log_artifact(mode_path)
    
    momentum_modes_base = os.path.join(plots_dir, "momentum_modes")
    plot_modes(pic.ts, pic.momentum, max_mode_spect=10, max_mode_time=5, boxsize=inputs.boxsize, num=4, zero_mean=True, save_path=momentum_modes_base)
    for suffix in ["_spectrum.png", "_evolution.png"]:
        mode_path = momentum_modes_base + suffix
        if os.path.exists(mode_path):
            log_artifact(mode_path)
    
    energy_modes_base = os.path.join(plots_dir, "energy_modes")
    plot_modes(pic.ts, pic.energy, max_mode_spect=10, max_mode_time=5, boxsize=inputs.boxsize, num=4, zero_mean=True, save_path=energy_modes_base)
    for suffix in ["_spectrum.png", "_evolution.png"]:
        mode_path = energy_modes_base + suffix
        if os.path.exists(mode_path):
            log_artifact(mode_path)
    
    # Convert JAX arrays to numpy arrays for output
    return OutputSchema(
        train_losses=np.array(train_losses, dtype=np.float64),
        final_loss=float(train_losses[-1]) if len(train_losses) > 0 else 0.0,
        positions=np.array(pic.positions, dtype=np.float32),
        velocities=np.array(pic.velocities, dtype=np.float32),
        E_field=np.array(pic.E_field, dtype=np.float32),
        E_ext=np.array(pic.E_ext, dtype=np.float32),
        rho=np.array(pic.rho, dtype=np.float32),
        momentum=np.array(pic.momentum, dtype=np.float32),
        energy=np.array(pic.energy, dtype=np.float32),
        ts=np.array(pic.ts, dtype=np.float32)
    )
